# creating dataframe and adding multiple complex queries

In [1]:
import pandas as pd
import numpy as np

In [ ]:
arr=(np.random.rand(20,6)*10)

array([[4.17637032, 0.11829222, 1.60941948, 1.10455491, 3.03925965,
        0.74246341],
       [5.03339169, 9.8688443 , 8.86660212, 9.10784386, 2.54084422,
        0.87530441],
       [8.72998833, 3.5636579 , 0.17748807, 1.42375858, 1.99019157,
        1.70245203],
       [2.76244788, 6.40703888, 5.52883531, 1.28511237, 7.88264387,
        2.49041131],
       [6.85052537, 3.65974762, 6.20810268, 9.86189894, 0.58904136,
        5.02111924],
       [6.2793942 , 0.34352026, 4.06834509, 3.88680891, 8.45901213,
        3.50965625],
       [6.1362628 , 9.41381694, 0.34922676, 4.84757075, 2.48485756,
        0.56600594],
       [3.69564741, 5.01979666, 4.2109909 , 5.23602038, 9.3554069 ,
        2.58181476],
       [4.24450721, 5.87547947, 9.33035983, 8.66881371, 1.47347445,
        9.3319127 ],
       [5.09690504, 0.09545182, 7.4260846 , 8.62588471, 7.4269859 ,
        9.94299576],
       [7.10335245, 4.91664446, 3.51281139, 8.21319587, 2.89926774,
        4.08169999],
       [8.58197602, 5.99980732, 6.63010178, 4.74047402, 9.69560206,
        3.01395901],
       [6.75310884, 1.73761908, 2.739521  , 4.98849245, 8.89238167,
        2.62465654],
       [0.36765455, 6.14930791, 1.78223398, 5.15825295, 8.9645914 ,
        6.1380203 ],
       [5.51605795, 0.7484035 , 7.3426614 , 2.14289936, 6.74027578,
        4.08300394],
       [6.76346244, 9.77764703, 3.05391845, 2.27082185, 7.44962815,
        0.89749528],
       [5.08234816, 2.86091084, 3.36336787, 8.8215507 , 1.32977085,
        3.96733604],
       [9.74228107, 7.00577515, 4.74897461, 1.86088559, 6.32723232,
        6.40865037],
       [7.05166692, 0.66981317, 2.60318698, 1.91138152, 1.87831403,
        8.79714767],
       [0.82476789, 9.31049926, 4.24902502, 4.90273014, 2.9895029 ,
        1.56499237]])

## Making DataFrame

In [3]:
df = pd.DataFrame(arr)
df.columns=['a','b','c','d','e','f']
df

           a         b         c         d         e         f
0   4.176370  0.118292  1.609419  1.104555  3.039260  0.742463
1   5.033392  9.868844  8.866602  9.107844  2.540844  0.875304
2   8.729988  3.563658  0.177488  1.423759  1.990192  1.702452
3   2.762448  6.407039  5.528835  1.285112  7.882644  2.490411
4   6.850525  3.659748  6.208103  9.861899  0.589041  5.021119
5   6.279394  0.343520  4.068345  3.886809  8.459012  3.509656
6   6.136263  9.413817  0.349227  4.847571  2.484858  0.566006
7   3.695647  5.019797  4.210991  5.236020  9.355407  2.581815
8   4.244507  5.875479  9.330360  8.668814  1.473474  9.331913
9   5.096905  0.095452  7.426085  8.625885  7.426986  9.942996
10  7.103352  4.916644  3.512811  8.213196  2.899268  4.081700
11  8.581976  5.999807  6.630102  4.740474  9.695602  3.013959
12  6.753109  1.737619  2.739521  4.988492  8.892382  2.624657
13  0.367655  6.149308  1.782234  5.158253  8.964591  6.138020
14  5.516058  0.748404  7.342661  2.142899  6.740276  4.083004
15  6.763462  9.777647  3.053918  2.270822  7.449628  0.897495
16  5.082348  2.860911  3.363368  8.821551  1.329771  3.967336
17  9.742281  7.005775  4.748975  1.860886  6.327232  6.408650
18  7.051667  0.669813  2.603187  1.911382  1.878314  8.797148
19  0.824768  9.310499  4.249025  4.902730  2.989503  1.564992

## conditioning

In [4]:
# df.loc[(df['a']>2) & (df['d']<5)] # condition is applied here
# df=df.loc[(df['a']>2) & (df['d']<5),['f']]*100  # only data of f will be shown
# df.loc[(df['a'] > 2) & (df['d'] < 5),['a','d']] =123456
# df.loc[(df['a'] > 2) & (df['d'] < 5), ['a', 'd']]*100
# condition =(  (df['a'] > 2) & (df['d'] < 5))
# df.loc[condition] =8888
df.loc[(df['a']>3)&(df['b']>5),['a','b','c'],]
an=df.loc[(df['a']>3)&(df['b']>5),['a','b','c'],]
an.reset_index()# will start indexing from 0
an.loc[ :,['a']]=str('Animesh')
an

C:\Users\anime\AppData\Local\Temp\ipykernel_12056\3559671725.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Animesh' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  an.loc[ :,['a']]=str('Animesh')

          a         b         c
1   Animesh  9.868844  8.866602
6   Animesh  9.413817  0.349227
7   Animesh  5.019797  4.210991
8   Animesh  5.875479  9.330360
11  Animesh  5.999807  6.630102
15  Animesh  9.777647  3.053918
17  Animesh  7.005775  4.748975